### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by baddwin** [veritrans/SNAP-Magento#15]
Hi,
it seems this module is for Magento 1, isn't it?
while in your latest documentation[^1], there is a module for Magento 2.
is it a separate module, like premium module, or anything else?

[^1]: https://snap-docs.midtrans.com/docs-en.pdf

**Comment by rizdaprasetya** [comment]
Hi @baddwin 

For magento 2, please find the module here:
http://docs.midtrans.com/en/welcome/pluginlibrary.html
https://github.com/Midtrans/SNAP-Magento2
