### ISSUE TITLE
Does not work as intended with PHP FPM

### ISSUE THREAD

**Issue by AlexStansfield** [veritrans/SNAP-Magento#20]
Your early response method does not work as intended when using PHP FPM as the connection remains open and the webserver doesn't not send it until the entire request is done.

Consider adding:

`fastcgi_finish_request()`

here:

https://github.com/veritrans/SNAP-Magento/blob/ff02bd9b7ddb28f075fe80eca0004d29e8fd3fc2/app/code/community/Midtrans/Snap/controllers/PaymentController.php#L301

**Comment by carolus10benny** [comment]
Please strive to keep the response time of the the HTTP notifications under 5 seconds.
