### ISSUE TITLE
Fail to open snap popup because of wrong environment

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/SNAP-Magento#8]
When opening Snap popup, sometimes plugin fail to determine which environment to use (production or sandbox), suspected because this code `$env = Mage::getSingleton('checkout/session')->getEnv();` fail to get customer browser's session cookies (when browser cookies disabled or session changed/unstable).
code location reference: https://github.com/veritrans/SNAP-Magento/blob/76ee5bf3916b3b25f404fee9dac0561ae241054f/app/design/frontend/base/default/template/snap/open.phtml#L30

Suggestion,
maybe using:
`Mage::getStoreConfig('payment/snap/environment')` ✅ 
instead of:
`Mage::getSingleton('checkout/session')->getEnv()` ❌ 
to get which payment environment, this could be more reliable than getting from browser cookies.

**Comment by harrypujianto** [comment]
it suppose to be that way.. Thx for the input.. the code has been fixed
